Add 3x3x3 Team-Blind and Team-Blind Old Style icons
cubing/icons pull request #106
Opened 2023-09-05 21:23 UTC by dmint789

This solves issue #100. The design was briefly discussed in issue #105. The convention will now be that one circle represents one person, which other team event icons can also follow. Team-Blind Old Style is intended to be used [here](https://cubingcontests.com/rankings/333tbfo/single). Old Style refers to Team-Blind with inspection, whereas the new format on cubingcontests.com is without it, so I want to use this old style icon for the old format.

Previews:

![333tbf](https://github.com/cubing/icons/assets/53250435/0f982d6d-2358-438b-977a-5d2ed6929ad0)

![333tbfo](https://github.com/cubing/icons/assets/53250435/6ecca482-6038-4c08-8c91-521538a4e7d5)

2023-09-05 23:36 UTC, jfly commented on svgs/unofficial/333tbf.svg
Out of curiosity, why did you decide to turn this upside-down compared to what you've got [on funcubing](https://funcubing.org/competitions/rankings)?

![image](https://github.com/cubing/icons/assets/277474/36dd2d9b-efb5-4889-b3b1-a8326141c0af)

2023-09-06 02:03 UTC, lgarron commented
I am unfortunately opposed to this — this event is unofficial, so there isn't really an "old" version of the event. I also intend to keep advocating for "across the table" Team BLD to make it more practical to judge, and wouldn't want to see more and more "old" versions of events that aren't even official yet.

2023-09-06 02:04 UTC, lgarron commented on svgs/unofficial/333tbf.svg
Indeed, it's very cute that way!

2023-09-06 06:05 UTC, dmint789 commented on svgs/unofficial/333tbf.svg
I thought it looked better this way. It kinda bothered me that their version looks like a smiley face. If you guys prefer I'll change it back.

2023-09-06 06:08 UTC, dmint789 commented
> I am unfortunately opposed to an "old" version — this event is unofficial, so there isn't really an "old" version of the event. I also intend to keep advocating for "across the table" Team BLD to make it more practical to judge, and wouldn't want to see more and more "old" versions of events that aren't even official yet.

I understand, but I just want to use this for my own website. I am not insisting that everyone else uses it.

I do think inspectionless team blind is a better event though, because the way it was with inspection, it just turned into 3bld with one competitor telling the other the full memo, and I think it lost most of its value as a team event because of that. Without inspection it seems like this event will have more variety in terms of methods.

2023-09-08 19:36 UTC, dmint789 commented
I have updated the icons as requested. @jfly is this good to merge now? Preview:

![333tbf](https://github.com/cubing/icons/assets/53250435/256f1055-1c23-47bb-9bc1-ec5410da4542)

2023-09-08 19:53 UTC, lgarron requested changes
Sorry for being sporadically active.

I definitely want to see a team BLD icon and I think the two-dot smiley is quite nice. But I still have two concerns about landing:

- I am strongly against an "old" icon for team BLD in this repo at the moment. (Perhaps this can be solved by supporting some transformations outside of assigning icons, like putting a strike through any icon.)
- I would really like to avoid cryptically short event IDs going forward, particularly if they don't match up with what people actually call events — it would be like using 3-letter variable names in programming because they had to do it in the 80's. I'd strongly prefer `333_team_bld` or at least `333_team_bf`.

@jfly, what's your take on these concerns?

2023-09-08 20:17 UTC, jfly commented
> I am strongly against an "old" icon for team BLD in this repo at the moment

I agree. I'd prefer to reserve that for events that were once WCA official and are no longer official.

@dmint789, how about we rework this PR to just add one event icon (333_team_bld). It's an unofficial event without regulations, I don't think this repo should be in the business of distinguishing between the various regulations that have been invented for unofficial events.

> I would really like to avoid cryptically short event IDs going forward

It's amusing to me that the icons repo might be the place that sets the standard for these codes in the future! I agree that the 3-4 character codes are overly obtuse. I vote for `333_team_bld`.

2023-09-08 20:34 UTC, dmint789 commented
We have to at least use kebab-case (333-team-bld) to stay consistent, since 333-mirror-blocks uses kebab-case. @jfly I also REALLY like the idea of cubing icons setting naming standards. You should add a small section about that. I, for one, got confused at first, cause I thought the word "unofficial" was part of the event names. And fine, I'll just use my own icon for old style, you don't need to make the repo confusing due to my website's quirk.

2023-09-08 20:36 UTC, dmint789 commented
Done

2023-09-08 20:36 UTC, jfly approved these changes

2023-09-08 20:37 UTC, lgarron approved these changes
😀

2023-09-08 20:38 UTC, dmint789 commented
Is one of you guys supposed to run the workflow or how does that work?

2023-09-08 20:38 UTC, jfly commented
> You should add a small section about that. I, for one, got confused at first, cause I thought the word "unofficial" was part of the event names

Yeah, I can see how that would be confusing! Would you be up for adding a blurp about the structure of this repo to the READMe?

2023-09-08 20:39 UTC, dmint789 commented
> > You should add a small section about that. I, for one, got confused at first, cause I thought the word "unofficial" was part of the event names
> 
> Yeah, I can see how that would be confusing! Would you be up for adding a blurp about the structure of this repo to the READMe?

Sure. You mean the main README of the repo? Is that connected to the website's front page?

2023-09-08 20:48 UTC, jfly commented
> Sure. You mean the main README of the repo? Is that connected to the website's front page?

After thinking about this a bit, I think this is a bit of a hairier problem than I realized. Let's continue this discussion over on https://github.com/cubing/icons/issues/108.

2023-09-08 20:48 UTC, dmint789 commented
Is this PR good to be merged now? Are we gonna stick with kebab-case or switch to snake_case?

2023-09-08 20:49 UTC, merged

2023-09-08 20:50 UTC, jfly commented
LGTM! Just merged it =)